// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCefuO4ZU3q4eCvDbxa5dEgb2m7T37FwX4',
    appId: '1:1001226096161:web:ac5555af420901f70f9d60',
    messagingSenderId: '1001226096161',
    projectId: 'yalapay-349f0',
    authDomain: 'yalapay-349f0.firebaseapp.com',
    storageBucket: 'yalapay-349f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-0BoPzd2DXfm3ipDUgoH86osLojLq6gU',
    appId: '1:1001226096161:android:8d3ffa681fcbee7e0f9d60',
    messagingSenderId: '1001226096161',
    projectId: 'yalapay-349f0',
    storageBucket: 'yalapay-349f0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4K3QGFFBjiPhJYVgNuzikQ3q2wCOYpns',
    appId: '1:1001226096161:ios:9a6e87a0869a7ee70f9d60',
    messagingSenderId: '1001226096161',
    projectId: 'yalapay-349f0',
    storageBucket: 'yalapay-349f0.firebasestorage.app',
    iosBundleId: 'com.example.yalaPay',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4K3QGFFBjiPhJYVgNuzikQ3q2wCOYpns',
    appId: '1:1001226096161:ios:9a6e87a0869a7ee70f9d60',
    messagingSenderId: '1001226096161',
    projectId: 'yalapay-349f0',
    storageBucket: 'yalapay-349f0.firebasestorage.app',
    iosBundleId: 'com.example.yalaPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSkFhNAWeAp7Yquz2GAwNB9SfivKa1aqI',
    appId: '1:1001226096161:web:c2a1459da73a42280f9d60',
    messagingSenderId: '1001226096161',
    projectId: 'yalapay-349f0',
    authDomain: 'yalapay-349f0.firebaseapp.com',
    storageBucket: 'yalapay-349f0.firebasestorage.app',
  );

}